/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApprovalAttachment: typeof import('./components/approval/ApprovalAttachment.vue')['default']
    ApprovalComment: typeof import('./components/approval/ApprovalComment.vue')['default']
    ApprovalConfig: typeof import('./components/workflow/configs/ApprovalConfig.vue')['default']
    BaseConfig: typeof import('./components/workflow/configs/BaseConfig.vue')['default']
    ConditionConfig: typeof import('./components/workflow/configs/ConditionConfig.vue')['default']
    DocumentPreview: typeof import('./components/document/common/DocumentPreview.vue')['default']
    DocumentUploader: typeof import('./components/document/common/DocumentUploader.vue')['default']
    DynamicForm: typeof import('./components/dynamic-form/DynamicForm.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTree: typeof import('element-plus/es')['ElTree']
    ErrorBoundary: typeof import('./components/common/ErrorBoundary.vue')['default']
    ExcelExporter: typeof import('./components/document/excel/ExcelExporter.vue')['default']
    ExcelFieldMapper: typeof import('./components/document/excel/ExcelFieldMapper.vue')['default']
    ExcelImporter: typeof import('./components/document/excel/ExcelImporter.vue')['default']
    ExcelPreview: typeof import('./components/document/excel/ExcelPreview.vue')['default']
    FormDesigner: typeof import('./components/form/FormDesigner.vue')['default']
    NodeConfigPanel: typeof import('./components/workflow/NodeConfigPanel.vue')['default']
    PdfThumbnail: typeof import('./components/document/pdf/PdfThumbnail.vue')['default']
    PdfToolbar: typeof import('./components/document/pdf/PdfToolbar.vue')['default']
    PdfViewer: typeof import('./components/document/pdf/PdfViewer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WorkflowCanvas: typeof import('./components/workflow/WorkflowCanvas.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
