/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApprovalAttachment: typeof import('./components/approval/ApprovalAttachment.vue')['default']
    ApprovalComment: typeof import('./components/approval/ApprovalComment.vue')['default']
    ApprovalNode: typeof import('./components/workflow/nodes/ApprovalNode.vue')['default']
    BarChart: typeof import('./components/charts/BarChart.vue')['default']
    CcNode: typeof import('./components/workflow/nodes/CcNode.vue')['default']
    ConditionNode: typeof import('./components/workflow/nodes/ConditionNode.vue')['default']
    DynamicForm: typeof import('./components/dynamic-form/DynamicForm.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTag: typeof import('element-plus/es')['ElTag']
    EndNode: typeof import('./components/workflow/nodes/EndNode.vue')['default']
    ErrorBoundary: typeof import('./components/common/ErrorBoundary.vue')['default']
    LineChart: typeof import('./components/charts/LineChart.vue')['default']
    NodeConfigPanel: typeof import('./components/workflow/NodeConfigPanel.vue')['default']
    PieChart: typeof import('./components/charts/PieChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StartNode: typeof import('./components/workflow/nodes/StartNode.vue')['default']
    WorkflowCanvas: typeof import('./components/workflow/WorkflowCanvas.vue')['default']
  }
}
