import type { ApprovalRecord, CCRecord, Department, DictionaryItem, LoginLog, MessageRecord, OperationLog, WorkbenchStats } from './types'
import type { WorkflowDefinition } from '@/types/workflow'
import type { Application, ApplicationStats, ApplicationVersion, ApplicationTemplate, TemplateReview, TemplateInstallRecord } from '@/types/application'
import type { FormSchema } from '@/types/form-schema'

export const mockDepartments: Department[] = [
  {
    id: '1',
    name: '技术部',
    children: [
      { id: '1-1', name: '前端组', parentId: '1' },
      { id: '1-2', name: '后端组', parentId: '1' },
    ],
  },
  {
    id: '2',
    name: '产品部',
    children: [{ id: '2-1', name: '产品设计组', parentId: '2' }],
  },
  {
    id: '3',
    name: '人事部',
  },
]

export const mockDictItems: Record<string, DictionaryItem[]> = {
  approval_type: [
    {
      id: '1',
      dictType: 'approval_type',
      dictCode: 'leave',
      dictLabel: '请假申请',
      dictValue: 'leave',
    },
    {
      id: '2',
      dictType: 'approval_type',
      dictCode: 'expense',
      dictLabel: '报销申请',
      dictValue: 'expense',
    },
    {
      id: '3',
      dictType: 'approval_type',
      dictCode: 'purchase',
      dictLabel: '采购申请',
      dictValue: 'purchase',
    },
  ],
  status: [
    { id: '4', dictType: 'status', dictCode: '1', dictLabel: '启用', dictValue: '1' },
    { id: '5', dictType: 'status', dictCode: '0', dictLabel: '禁用', dictValue: '0' },
  ],
}

export const mockApprovalRecords: ApprovalRecord[] = [
  {
    id: 'APPROVE-20260228-001',
    title: '第一季度办公用品采购申请',
    type: 'purchase',
    status: 'pending',
    applicant: '李四',
    applicantAvatar: 'https://api.multiavatar.com/李四.png',
    applyTime: '2026-02-28 09:30:00',
    currentNodeName: '部门联合会签',
    amount: 5000,
    isUrgent: false,
    deadlineAt: '2026-12-31 23:59:59',
    workflowInstance: {
      currentNodeId: 'node-approval-001',
      currentNodeMode: 'and',
      currentNodeAssignees: [
        { id: 'user-001', name: 'admin' },
        { id: 'user-002', name: 'manager' },
      ],
      progress: {
        completed: 0,
        total: 2,
      },
      tasks: [
        {
          id: 'task-001-admin',
          nodeId: 'node-approval-001',
          handlerId: 'user-001',
          handlerName: 'admin',
          status: 'pending',
          taskStatus: 'pending',
        },
        {
          id: 'task-001-manager',
          nodeId: 'node-approval-001',
          handlerId: 'user-002',
          handlerName: 'manager',
          status: 'pending',
          taskStatus: 'pending',
        },
      ],
    },
  },
  {
    id: 'APPROVE-20260228-002',
    title: '张三的年假申请（或签）',
    type: 'leave',
    status: 'pending',
    applicant: '张三',
    applicantAvatar: 'https://api.multiavatar.com/张三.png',
    applyTime: '2026-02-28 08:15:00',
    currentNodeName: '部门经理或签',
    amount: 5,
    isUrgent: false,
    deadlineAt: '2026-12-31 23:59:59',
    workflowInstance: {
      currentNodeId: 'node-approval-002',
      currentNodeMode: 'or',
      currentNodeAssignees: [
        { id: 'user-001', name: 'admin' },
        { id: 'user-002', name: 'manager' },
      ],
      progress: {
        completed: 0,
        total: 2,
      },
      tasks: [
        {
          id: 'task-002-admin',
          nodeId: 'node-approval-002',
          handlerId: 'user-001',
          handlerName: 'admin',
          status: 'pending',
          taskStatus: 'pending',
        },
        {
          id: 'task-002-manager',
          nodeId: 'node-approval-002',
          handlerId: 'user-002',
          handlerName: 'manager',
          status: 'pending',
          taskStatus: 'pending',
        },
      ],
    },
  },
  {
    id: 'APPROVE-20260115-ESC001',
    title: '服务器紧急扩容申请（超时升级样例）',
    type: 'purchase',
    status: 'pending',
    applicant: '王五',
    applicantAvatar: 'https://api.multiavatar.com/王五.png',
    applyTime: '2026-01-15 09:00:00',
    currentNodeName: '部门经理审批',
    amount: 18800,
    isUrgent: true,
    deadlineAt: '2026-01-17 09:00:00',
    workflowInstance: {
      currentNodeId: 'node-approval-esc-001',
      currentNodeMode: 'or',
      currentNodeAssignees: [
        { id: 'user-001', name: 'admin' },
      ],
      progress: {
        completed: 0,
        total: 1,
      },
      tasks: [
        {
          id: 'task-esc-001-admin',
          nodeId: 'node-approval-esc-001',
          handlerId: 'user-001',
          handlerName: 'admin',
          status: 'pending',
          taskStatus: 'pending',
        },
      ],
    },
  },
  {
    id: 'APPROVE-20260227-001',
    title: '王五的差旅费报销',
    type: 'expense',
    status: 'approved',
    applicant: '王五',
    applicantAvatar: 'https://api.multiavatar.com/王五.png',
    applyTime: '2026-02-27 14:20:00',
    currentNodeName: '财务审批',
    amount: 1200,
    isUrgent: false,
    workflowInstance: {
      currentNodeId: 'node-approval-003',
      tasks: [
        { id: 'task-003', handlerId: 'user-003', status: 'approved' },
      ],
    },
  },
  {
    id: 'APPROVE-20260226-001',
    title: '项目采购申请 - 服务器设备',
    type: 'purchase',
    status: 'rejected',
    applicant: '赵六',
    applicantAvatar: 'https://api.multiavatar.com/赵六.png',
    applyTime: '2026-02-26 10:00:00',
    currentNodeName: '采购部审批',
    amount: 25000,
    isUrgent: true,
    workflowInstance: {
      currentNodeId: 'node-approval-004',
      tasks: [
        { id: 'task-004', handlerId: 'user-004', status: 'rejected' },
      ],
    },
  },
]

export const mockWorkbenchStats: WorkbenchStats = {
  pendingCount: 3,
  myApplicationCount: 5,
  approvedCount: 12,
  rejectedCount: 2,
}

/**
 * Mock 流程定义数据
 */
export const mockWorkflowDefinitions: WorkflowDefinition[] = [
  {
    id: 'wf-001',
    name: '请假审批流程',
    description: '适用于所有员工的请假申请审批',
    status: 'active',
    formSchemaId: 'leave',
    nodes: [
      {
        id: 'start-001',
        type: 'start',
        name: '发起节点',
        description: '员工发起请假申请',
        position: { x: 400, y: 100 },
        enabled: true,
      },
      {
        id: 'approval-001',
        type: 'approval',
        name: '部门经理审批',
        description: '直属部门经理审批',
        handler: {
          type: 'deptManager',
          mode: 'and',
          assignees: [
            { id: 'user-001', name: 'admin' },
            { id: 'user-002', name: 'manager' },
          ],
        },
        formSchemaId: 'leave-form',
        position: { x: 400, y: 250 },
        enabled: true,
      },
      {
        id: 'approval-002',
        type: 'approval',
        name: 'HR 审批',
        description: '人事部备案',
        handler: { type: 'role', roleIds: ['hr'], mode: 'or' },
        formSchemaId: 'leave-form',
        // ✅ HR 节点：只读查看leaveType，必填HR意见
        formPermissions: {
          leaveType: 'readonly',      // HR 不允许修改请假类型
          days: 'readonly',           // 天数只读
          manager_comment: 'readonly', // 上一级意见只读
          hr_comment: 'required',     // HR 意见必填
          amount: 'readonly',         // 金额只读（后端计算）
          internal_notes: 'hidden',   // 内部备注对 HR 隐藏（敏感字段）
        },
        position: { x: 400, y: 400 },
        enabled: true,
      },
      {
        id: 'end-001',
        type: 'end',
        name: '结束节点',
        description: '流程结束',
        position: { x: 400, y: 550 },
        enabled: true,
      },
    ],
    edges: [
      { id: 'edge-001', source: 'start-001', target: 'approval-001' },
      { id: 'edge-002', source: 'approval-001', target: 'approval-002' },
      { id: 'edge-003', source: 'approval-002', target: 'end-001' },
    ],
    createdBy: 'admin',
    createdAt: '2026-01-15 10:00:00',
    updatedAt: '2026-02-20 14:30:00',
    version: 2,
  },
  {
    id: 'wf-002',
    name: '报销审批流程',
    description: '适用于所有费用报销申请',
    status: 'active',
    formSchemaId: 'expense',
    nodes: [
      {
        id: 'start-002',
        type: 'start',
        name: '发起节点',
        position: { x: 400, y: 100 },
        enabled: true,
      },
      {
        id: 'approval-003',
        type: 'approval',
        name: '财务审批',
        handler: {
          type: 'role',
          roleIds: ['finance'],
          mode: 'or',
          assignees: [
            { id: 'user-001', name: 'admin' },
            { id: 'user-002', name: 'manager' },
          ],
        },
        position: { x: 400, y: 300 },
        enabled: true,
      },
      {
        id: 'end-002',
        type: 'end',
        name: '结束节点',
        position: { x: 400, y: 500 },
        enabled: true,
      },
    ],
    edges: [
      { id: 'edge-004', source: 'start-002', target: 'approval-003' },
      { id: 'edge-005', source: 'approval-003', target: 'end-002' },
    ],
    createdBy: 'admin',
    createdAt: '2026-01-10 09:00:00',
    updatedAt: '2026-02-18 11:20:00',
    version: 1,
  },
]

/**
 * Mock 表单 Schema 列表
 */
export const mockFormSchemas: Array<{ id: string, name: string }> = [
  { id: 'leave-form', name: '请假申请表' },
  { id: 'expense-form', name: '报销申请表' },
  { id: 'purchase-form', name: '采购申请表' },
  { id: 'overtime-form', name: '加班申请表' },
]

// ==================== 发起审批 Mock 数据 ====================
/**
 * 流程列表 (用于发起审批页面)
 */
export const mockWorkflowList = [
  {
    id: 'wf-leave-001',
    name: '请假申请',
    description: '员工请病假、事假、年假等',
    isDefault: true,
    schemaId: 'leave-form',
    icon: 'Calendar',
  },
  {
    id: 'wf-reimbursement-001',
    name: '报销申请',
    description: '差旅费、业务招待费等报销',
    isDefault: false,
    schemaId: 'expense-form',
    icon: 'Money',
  },
  {
    id: 'wf-purchase-001',
    name: '采购申请',
    description: '办公用品、设备采购',
    isDefault: false,
    schemaId: 'purchase-form',
    icon: 'Cart',
  },
]

/**
 * 请假表单 Schema
 */
export const mockLeaveSchema = {
  fields: [
    {
      key: 'leaveType',
      label: '请假类型',
      type: 'select',
      options: [
        { label: '病假', value: 'sick' },
        { label: '事假', value: 'personal' },
        { label: '年假', value: 'annual' },
      ],
      required: true,
    },
    {
      key: 'days',
      label: '请假天数',
      type: 'number',
      required: true,
      componentProps: { min: 0.5, step: 0.5, placeholder: '请输入请假天数' },
    },
    {
      key: 'startTime',
      label: '开始时间',
      type: 'date',
      required: true,
      componentProps: { placeholder: '请选择开始时间' },
    },
    {
      key: 'reason',
      label: '请假事由',
      type: 'textarea',
      required: true,
      placeholder: '请详细说明请假原因',
    },
  ],
  labelWidth: '120px',
}

/**
 * 报销表单 Schema
 */
export const mockExpenseSchema = {
  fields: [
    {
      key: 'expenseType',
      label: '报销类型',
      type: 'select',
      options: [
        { label: '差旅费', value: 'travel' },
        { label: '业务招待费', value: 'dinner' },
        { label: '交通费', value: 'transport' },
      ],
      required: true,
    },
    {
      key: 'amount',
      label: '报销金额',
      type: 'inputNumber',
      required: true,
      componentProps: { min: 0, placeholder: '请输入报销金额' },
    },
    {
      key: 'date',
      label: '发生日期',
      type: 'date',
      required: true,
      componentProps: { placeholder: '请选择发生日期' },
    },
    {
      key: 'description',
      label: '报销说明',
      type: 'textarea',
      required: true,
      placeholder: '请详细说明报销详情',
    },
  ],
  labelWidth: '120px',
}

/**
 * 采购表单 Schema
 */
export const mockPurchaseSchema = {
  fields: [
    {
      key: 'projectName',
      label: '项目名称',
      type: 'input',
      required: true,
      placeholder: '请输入项目名称',
    },
    {
      key: 'items',
      label: '采购清单',
      type: 'textarea',
      required: true,
      placeholder: '请逐项列出采购物品',
    },
    {
      key: 'budget',
      label: '预算金额',
      type: 'inputNumber',
      required: true,
      componentProps: { min: 0, placeholder: '请输入预算金额' },
    },
    {
      key: 'needByDate',
      label: ' required 日期',
      type: 'date',
      required: true,
      componentProps: { placeholder: '请选择需要日期' },
    },
  ],
  labelWidth: '120px',
}

// ==================== 消息中心 Mock 数据 ====================
/**
 * 消息记录列表
 */
export const mockMessageRecords: MessageRecord[] = [
  {
    id: 'msg-001',
    title: '审批通过通知',
    content: '您的请假申请已通过审批',
    type: 'approval',
    relatedId: 'APPROVE-1734567890123-abc123',
    read: false,
    createdAt: '2024-01-15 14:30:00',
    priority: 'normal',
  },
  {
    id: 'msg-002',
    title: '审批驳回通知',
    content: '您的报销申请已被驳回，原因：缺少发票',
    type: 'approval',
    relatedId: 'APPROVE-1734567890124-def456',
    read: false,
    createdAt: '2024-01-15 10:20:00',
    priority: 'high',
  },
  {
    id: 'msg-003',
    title: '待审批提醒',
    content: '您有一条新的审批待处理：张三的请假申请',
    type: 'approval',
    relatedId: 'APPROVE-1734567890125-ghi789',
    read: true,
    readTime: '2024-01-15 09:00:00',
    createdAt: '2024-01-15 08:45:00',
    priority: 'normal',
  },
  {
    id: 'msg-004',
    title: '系统维护通知',
    content: '系统将于今晚 22:00-24:00 进行维护升级，请提前保存工作',
    type: 'system',
    read: false,
    createdAt: '2024-01-14 16:00:00',
    priority: 'high',
  },
  {
    id: 'msg-005',
    title: '抄送通知',
    content: '李四的采购申请已抄送给您',
    type: 'cc',
    relatedId: 'APPROVE-1734567890126-jkl012',
    read: true,
    readTime: '2024-01-14 11:30:00',
    createdAt: '2024-01-14 11:15:00',
    priority: 'low',
  },
  {
    id: 'msg-006',
    title: '审批转交通知',
    content: '王五已将审批转交给您处理',
    type: 'approval',
    relatedId: 'APPROVE-1734567890127-mno345',
    read: false,
    createdAt: '2024-01-14 09:30:00',
    priority: 'high',
  },
  {
    id: 'msg-007',
    title: '催办提醒',
    content: '您的审批任务已被催办，请尽快处理',
    type: 'approval',
    relatedId: 'APPROVE-1734567890128-pqr678',
    read: false,
    createdAt: '2024-01-13 15:20:00',
    priority: 'high',
  },
  {
    id: 'msg-008',
    title: '系统更新通知',
    content: '新版本已发布，增加了工作流版本管理功能',
    type: 'system',
    read: true,
    readTime: '2024-01-13 10:00:00',
    createdAt: '2024-01-13 09:00:00',
    priority: 'normal',
  },
  {
    id: 'msg-009',
    title: '审批撤回通知',
    content: '赵六已撤回审批申请',
    type: 'approval',
    relatedId: 'APPROVE-1734567890129-stu901',
    read: true,
    readTime: '2024-01-12 16:45:00',
    createdAt: '2024-01-12 16:30:00',
    priority: 'normal',
  },
  {
    id: 'msg-010',
    title: '抄送通知',
    content: '孙七的请假申请已抄送给您',
    type: 'cc',
    relatedId: 'APPROVE-1734567890130-vwx234',
    read: false,
    createdAt: '2024-01-12 14:00:00',
    priority: 'low',
  },
]

// ==================== 登录日志 Mock 数据 ====================
/**
 * 登录日志列表
 */
export const mockLoginLogs: LoginLog[] = [
  {
    id: 'LOGIN-001',
    userId: 'user-001',
    username: 'admin',
    ipAddress: '192.168.1.100',
    location: '北京市',
    device: 'PC',
    os: 'Windows',
    browser: 'Chrome',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
    status: 'success',
    loginTime: '2024-01-15 09:00:00',
    logoutTime: '2024-01-15 18:00:00',
    duration: 32400,
  },
  {
    id: 'LOGIN-002',
    userId: 'user-002',
    username: 'zhangsan',
    ipAddress: '192.168.1.101',
    location: '上海市',
    device: 'PC',
    os: 'macOS',
    browser: 'Safari',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15',
    status: 'success',
    loginTime: '2024-01-15 08:30:00',
    logoutTime: '2024-01-15 17:30:00',
    duration: 32400,
  },
  {
    id: 'LOGIN-003',
    userId: 'user-003',
    username: 'lisi',
    ipAddress: '192.168.1.102',
    location: '广州市',
    device: 'Mobile',
    os: 'Android',
    browser: 'Chrome',
    userAgent: 'Mozilla/5.0 (Linux; Android 11; SM-G991B) AppleWebKit/537.36',
    status: 'failed',
    failReason: '密码错误',
    loginTime: '2024-01-15 08:00:00',
  },
  {
    id: 'LOGIN-004',
    userId: 'user-004',
    username: 'wangwu',
    ipAddress: '192.168.1.103',
    location: '深圳市',
    device: 'PC',
    os: 'Windows',
    browser: 'Edge',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0',
    status: 'success',
    loginTime: '2024-01-14 14:20:00',
    logoutTime: '2024-01-14 18:00:00',
    duration: 13200,
  },
  {
    id: 'LOGIN-005',
    userId: 'user-005',
    username: 'zhaoliu',
    ipAddress: '192.168.1.104',
    location: '杭州市',
    device: 'Tablet',
    os: 'iOS',
    browser: 'Safari',
    userAgent: 'Mozilla/5.0 (iPad; CPU OS 15_0 like Mac OS X) AppleWebKit/605.1.15',
    status: 'success',
    loginTime: '2024-01-14 10:00:00',
    logoutTime: '2024-01-14 12:00:00',
    duration: 7200,
  },
  {
    id: 'LOGIN-006',
    userId: 'user-001',
    username: 'admin',
    ipAddress: '192.168.1.100',
    location: '北京市',
    device: 'PC',
    os: 'Windows',
    browser: 'Chrome',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
    status: 'failed',
    failReason: '账号被锁定',
    loginTime: '2024-01-14 07:00:00',
  },
  {
    id: 'LOGIN-007',
    userId: 'user-006',
    username: 'sunqi',
    ipAddress: '192.168.1.105',
    location: '成都市',
    device: 'PC',
    os: 'Linux',
    browser: 'Firefox',
    userAgent: 'Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0',
    status: 'success',
    loginTime: '2024-01-13 09:30:00',
    logoutTime: '2024-01-13 18:30:00',
    duration: 32400,
  },
  {
    id: 'LOGIN-008',
    userId: 'user-002',
    username: 'zhangsan',
    ipAddress: '192.168.1.101',
    location: '上海市',
    device: 'Mobile',
    os: 'iOS',
    browser: 'Safari',
    userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 15_0 like Mac OS X) AppleWebKit/605.1.15',
    status: 'success',
    loginTime: '2024-01-13 08:00:00',
    logoutTime: '2024-01-13 09:00:00',
    duration: 3600,
  },
  {
    id: 'LOGIN-009',
    userId: 'user-007',
    username: 'zhouba',
    ipAddress: '192.168.1.106',
    location: '武汉市',
    device: 'PC',
    os: 'Windows',
    browser: 'Chrome',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
    status: 'failed',
    failReason: '验证码错误',
    loginTime: '2024-01-12 16:00:00',
  },
  {
    id: 'LOGIN-010',
    userId: 'user-008',
    username: 'wujiu',
    ipAddress: '192.168.1.107',
    location: '南京市',
    device: 'PC',
    os: 'macOS',
    browser: 'Chrome',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
    status: 'success',
    loginTime: '2024-01-12 09:00:00',
    logoutTime: '2024-01-12 17:00:00',
    duration: 28800,
  },
]

// ==================== 操作日志 Mock 数据 ====================
/**
 * 操作日志列表
 */
export const mockOperationLogs: OperationLog[] = [
  {
    id: 'OP-001',
    operatorId: 'user-001',
    operatorName: 'admin',
    operationType: 'approve',
    module: 'approval',
    operationContent: '审批通过了张三的请假申请',
    targetId: 'APPROVE-001',
    targetType: 'approval',
    ipAddress: '192.168.1.100',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
    operatedAt: '2024-01-15 14:30:00',
    duration: 120,
    status: 'success',
  },
  {
    id: 'OP-002',
    operatorId: 'user-001',
    operatorName: 'admin',
    operationType: 'create',
    module: 'user',
    operationContent: '创建了新用户：李四',
    targetId: 'user-010',
    targetType: 'user',
    ipAddress: '192.168.1.100',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
    requestParams: { username: 'lisi', name: '李四', role: 'user' },
    operatedAt: '2024-01-15 10:20:00',
    duration: 85,
    status: 'success',
  },
  {
    id: 'OP-003',
    operatorId: 'user-002',
    operatorName: 'zhangsan',
    operationType: 'update',
    module: 'workflow',
    operationContent: '修改了请假审批流程',
    targetId: 'wf-001',
    targetType: 'workflow',
    ipAddress: '192.168.1.101',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15',
    beforeData: { name: '请假流程', status: 'draft' },
    afterData: { name: '请假审批流程', status: 'active' },
    operatedAt: '2024-01-15 09:15:00',
    duration: 200,
    status: 'success',
  },
  {
    id: 'OP-004',
    operatorId: 'user-001',
    operatorName: 'admin',
    operationType: 'delete',
    module: 'role',
    operationContent: '删除了角色：临时角色',
    targetId: 'role-999',
    targetType: 'role',
    ipAddress: '192.168.1.100',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
    operatedAt: '2024-01-14 16:45:00',
    duration: 50,
    status: 'success',
  },
  {
    id: 'OP-005',
    operatorId: 'user-003',
    operatorName: 'wangwu',
    operationType: 'reject',
    module: 'approval',
    operationContent: '驳回了赵六的报销申请',
    targetId: 'APPROVE-002',
    targetType: 'approval',
    ipAddress: '192.168.1.103',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
    operatedAt: '2024-01-14 14:20:00',
    duration: 95,
    status: 'success',
  },
  {
    id: 'OP-006',
    operatorId: 'user-001',
    operatorName: 'admin',
    operationType: 'update',
    module: 'user',
    operationContent: '更新了用户信息：张三',
    targetId: 'user-002',
    targetType: 'user',
    ipAddress: '192.168.1.100',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
    beforeData: { name: '张三', email: 'zhangsan@example.com' },
    afterData: { name: '张三', email: 'zhangsan@company.com' },
    operatedAt: '2024-01-14 11:30:00',
    duration: 75,
    status: 'success',
  },
  {
    id: 'OP-007',
    operatorId: 'user-002',
    operatorName: 'zhangsan',
    operationType: 'transfer',
    module: 'approval',
    operationContent: '将审批转交给了李四',
    targetId: 'APPROVE-003',
    targetType: 'approval',
    ipAddress: '192.168.1.101',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15',
    operatedAt: '2024-01-13 15:00:00',
    duration: 60,
    status: 'success',
  },
  {
    id: 'OP-008',
    operatorId: 'user-001',
    operatorName: 'admin',
    operationType: 'create',
    module: 'role',
    operationContent: '创建了新角色：财务专员',
    targetId: 'role-005',
    targetType: 'role',
    ipAddress: '192.168.1.100',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
    requestParams: { name: '财务专员', permissions: ['approval:view', 'approval:process'] },
    operatedAt: '2024-01-13 10:00:00',
    duration: 110,
    status: 'success',
  },
  {
    id: 'OP-009',
    operatorId: 'user-001',
    operatorName: 'admin',
    operationType: 'delete',
    module: 'user',
    operationContent: '删除用户失败：用户正在使用中',
    targetId: 'user-005',
    targetType: 'user',
    ipAddress: '192.168.1.100',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
    operatedAt: '2024-01-12 16:00:00',
    duration: 45,
    status: 'failed',
    errorMessage: '用户正在使用中，无法删除',
  },
  {
    id: 'OP-010',
    operatorId: 'user-004',
    operatorName: 'zhaoliu',
    operationType: 'approve',
    module: 'approval',
    operationContent: '审批通过了孙七的采购申请',
    targetId: 'APPROVE-004',
    targetType: 'approval',
    ipAddress: '192.168.1.104',
    userAgent: 'Mozilla/5.0 (iPad; CPU OS 15_0 like Mac OS X) AppleWebKit/605.1.15',
    operatedAt: '2024-01-12 09:30:00',
    duration: 150,
    status: 'success',
  },
]

/**
 * Mock 抄送记录数据
 */
export const mockCCRecords: CCRecord[] = [
  {
    id: 'CC-001',
    approvalId: 'APPROVE-001',
    title: '张三的请假申请',
    type: '请假申请',
    status: 'approved',
    applicant: '张三',
    applicantAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=zhangsan',
    ccTime: '2024-01-15 14:30:00',
    ccNodeName: '抄送人事部',
    read: false,
    description: '因个人事务请假3天',
  },
  {
    id: 'CC-002',
    approvalId: 'APPROVE-002',
    title: '李四的报销申请',
    type: '报销申请',
    status: 'approved',
    applicant: '李四',
    applicantAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=lisi',
    ccTime: '2024-01-15 10:20:00',
    ccNodeName: '抄送财务部',
    read: true,
    readTime: '2024-01-15 11:00:00',
    amount: 1500,
    description: '差旅费报销',
  },
  {
    id: 'CC-003',
    approvalId: 'APPROVE-003',
    title: '王五的采购申请',
    type: '采购申请',
    status: 'pending',
    applicant: '王五',
    applicantAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=wangwu',
    ccTime: '2024-01-14 16:45:00',
    ccNodeName: '抄送采购部',
    read: false,
    amount: 50000,
    description: '办公设备采购',
  },
  {
    id: 'CC-004',
    approvalId: 'APPROVE-004',
    title: '赵六的合同审批',
    type: '合同审批',
    status: 'approved',
    applicant: '赵六',
    applicantAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=zhaoliu',
    ccTime: '2024-01-14 09:15:00',
    ccNodeName: '抄送法务部',
    read: true,
    readTime: '2024-01-14 10:30:00',
    amount: 200000,
    description: '供应商合作合同',
  },
  {
    id: 'CC-005',
    approvalId: 'APPROVE-005',
    title: '孙七的用章申请',
    type: '用章申请',
    status: 'rejected',
    applicant: '孙七',
    applicantAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sunqi',
    ccTime: '2024-01-13 15:20:00',
    ccNodeName: '抄送行政部',
    read: false,
    description: '合同用章',
  },
  {
    id: 'CC-006',
    approvalId: 'APPROVE-006',
    title: '周八的出差申请',
    type: '出差申请',
    status: 'approved',
    applicant: '周八',
    applicantAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=zhouba',
    ccTime: '2024-01-13 11:00:00',
    ccNodeName: '抄送部门经理',
    read: true,
    readTime: '2024-01-13 14:00:00',
    description: '北京出差3天',
  },
  {
    id: 'CC-007',
    approvalId: 'APPROVE-007',
    title: '吴九的加班申请',
    type: '加班申请',
    status: 'approved',
    applicant: '吴九',
    applicantAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=wujiu',
    ccTime: '2024-01-12 18:30:00',
    ccNodeName: '抄送人事部',
    read: false,
    description: '项目紧急加班',
  },
  {
    id: 'CC-008',
    approvalId: 'APPROVE-008',
    title: '郑十的转正申请',
    type: '转正申请',
    status: 'pending',
    applicant: '郑十',
    applicantAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=zhengshi',
    ccTime: '2024-01-12 14:00:00',
    ccNodeName: '抄送HR',
    read: true,
    readTime: '2024-01-12 15:30:00',
    description: '试用期满转正',
  },
  {
    id: 'CC-009',
    approvalId: 'APPROVE-009',
    title: '陈十一的调岗申请',
    type: '调岗申请',
    status: 'approved',
    applicant: '陈十一',
    applicantAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=chenshiyi',
    ccTime: '2024-01-11 10:45:00',
    ccNodeName: '抄送部门负责人',
    read: true,
    readTime: '2024-01-11 16:00:00',
    description: '从前端组调至后端组',
  },
  {
    id: 'CC-010',
    approvalId: 'APPROVE-010',
    title: '刘十二的离职申请',
    type: '离职申请',
    status: 'approved',
    applicant: '刘十二',
    applicantAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=liushier',
    ccTime: '2024-01-10 09:00:00',
    ccNodeName: '抄送人事部',
    read: false,
    description: '个人原因离职',
  },
]

// ==================== 应用中心 Mock 数据 ====================

/**
 * Mock 应用列表
 */
export const mockApplications: Application[] = [
  {
    id: 'APP-001',
    name: '请假申请',
    description: '员工请病假、事假、年假等各类假期申请',
    icon: '🏖️',
    category: 'hr',
    status: 'published',
    formSchemaId: 'leave-form',
    workflowId: 'wf-leave-001',
    version: 3,
    currentVersionId: 'VER-001-003',
    usageCount: 156,
    approvalCount: 142,
    isDefault: true,
    isTemplate: false,
    allowCustomize: false,
    tags: ['人事', '常用'],
    createdBy: 'admin',
    createdAt: '2026-01-10 10:00:00',
    updatedBy: 'admin',
    updatedAt: '2026-03-15 14:30:00',
    publishedAt: '2026-01-10 15:00:00',
    publishedBy: 'admin',
  },
  {
    id: 'APP-002',
    name: '报销申请',
    description: '差旅费、业务招待费、交通费等各类费用报销',
    icon: '💰',
    category: 'finance',
    status: 'published',
    formSchemaId: 'expense-form',
    workflowId: 'wf-reimbursement-001',
    version: 2,
    currentVersionId: 'VER-002-002',
    usageCount: 89,
    approvalCount: 85,
    isDefault: true,
    isTemplate: false,
    allowCustomize: false,
    tags: ['财务', '常用'],
    createdBy: 'admin',
    createdAt: '2026-01-12 09:00:00',
    updatedBy: 'admin',
    updatedAt: '2026-02-20 11:20:00',
    publishedAt: '2026-01-12 10:00:00',
    publishedBy: 'admin',
  },
  {
    id: 'APP-003',
    name: '采购申请',
    description: '办公用品、设备、软件等采购申请',
    icon: '🛒',
    category: 'admin',
    status: 'published',
    formSchemaId: 'purchase-form',
    workflowId: 'wf-purchase-001',
    version: 1,
    currentVersionId: 'VER-003-001',
    usageCount: 45,
    approvalCount: 38,
    isDefault: false,
    isTemplate: false,
    allowCustomize: true,
    tags: ['行政', '采购'],
    createdBy: 'admin',
    createdAt: '2026-01-15 14:00:00',
    updatedBy: 'admin',
    updatedAt: '2026-01-15 14:00:00',
    publishedAt: '2026-01-15 16:00:00',
    publishedBy: 'admin',
  },
  {
    id: 'APP-004',
    name: '加班申请',
    description: '员工加班申请及调休管理',
    icon: '⏰',
    category: 'hr',
    status: 'published',
    formSchemaId: 'overtime-form',
    workflowId: 'wf-overtime-001',
    version: 1,
    currentVersionId: 'VER-004-001',
    usageCount: 67,
    approvalCount: 63,
    isDefault: false,
    isTemplate: false,
    allowCustomize: false,
    tags: ['人事', '考勤'],
    createdBy: 'admin',
    createdAt: '2026-01-20 10:30:00',
    updatedBy: 'admin',
    updatedAt: '2026-01-20 10:30:00',
    publishedAt: '2026-01-20 11:00:00',
    publishedBy: 'admin',
  },
  {
    id: 'APP-005',
    name: '合同审批',
    description: '各类合同签订审批流程',
    icon: '📄',
    category: 'approval',
    status: 'draft',
    formSchemaId: 'contract-form',
    workflowId: 'wf-contract-001',
    version: 1,
    currentVersionId: 'VER-005-001',
    usageCount: 0,
    approvalCount: 0,
    isDefault: false,
    isTemplate: false,
    allowCustomize: true,
    tags: ['审批', '合同'],
    createdBy: 'admin',
    createdAt: '2026-03-01 09:00:00',
    updatedBy: 'admin',
    updatedAt: '2026-03-10 16:45:00',
  },
]

/**
 * Mock 应用统计数据
 */
export const mockApplicationStats: ApplicationStats[] = [
  {
    applicationId: 'APP-001',
    totalSubmissions: 156,
    pendingCount: 8,
    approvedCount: 142,
    rejectedCount: 6,
    avgProcessTime: 4.5,
    avgApprovalTime: 3.2,
    dailySubmissions: [12, 15, 18, 14, 20, 16, 22],
    activeUsers: 45,
    topApplicants: [
      { userId: 'user-001', userName: '张三', count: 12 },
      { userId: 'user-002', userName: '李四', count: 10 },
      { userId: 'user-003', userName: '王五', count: 8 },
    ],
  },
  {
    applicationId: 'APP-002',
    totalSubmissions: 89,
    pendingCount: 4,
    approvedCount: 85,
    rejectedCount: 0,
    avgProcessTime: 6.8,
    avgApprovalTime: 5.5,
    dailySubmissions: [8, 10, 12, 9, 15, 11, 13],
    activeUsers: 32,
    topApplicants: [
      { userId: 'user-004', userName: '赵六', count: 15 },
      { userId: 'user-005', userName: '孙七', count: 11 },
      { userId: 'user-006', userName: '周八', count: 9 },
    ],
  },
  {
    applicationId: 'APP-003',
    totalSubmissions: 45,
    pendingCount: 3,
    approvedCount: 38,
    rejectedCount: 4,
    avgProcessTime: 12.5,
    avgApprovalTime: 10.2,
    dailySubmissions: [5, 6, 7, 5, 8, 6, 7],
    activeUsers: 18,
    topApplicants: [
      { userId: 'user-007', userName: '吴九', count: 8 },
      { userId: 'user-008', userName: '郑十', count: 6 },
      { userId: 'user-009', userName: '陈十一', count: 5 },
    ],
  },
  {
    applicationId: 'APP-004',
    totalSubmissions: 67,
    pendingCount: 2,
    approvedCount: 63,
    rejectedCount: 2,
    avgProcessTime: 2.8,
    avgApprovalTime: 1.5,
    dailySubmissions: [8, 9, 11, 8, 12, 10, 9],
    activeUsers: 28,
    topApplicants: [
      { userId: 'user-010', userName: '刘十二', count: 10 },
      { userId: 'user-011', userName: '黄十三', count: 8 },
      { userId: 'user-012', userName: '杨十四', count: 7 },
    ],
  },
]

/**
 * Mock 应用版本历史
 */
export const mockApplicationVersions: ApplicationVersion[] = [
  {
    id: 'VER-001-003',
    applicationId: 'APP-001',
    version: 3,
    versionName: 'v1.2.0',
    formSchemaSnapshot: {
      id: 'leave-form',
      name: '请假申请表',
      fields: [
        {
          id: 'leaveType',
          type: 'select',
          label: '请假类型',
          required: true,
          options: [
            { label: '病假', value: 'sick' },
            { label: '事假', value: 'personal' },
            { label: '年假', value: 'annual' },
          ],
        },
        {
          id: 'days',
          type: 'number',
          label: '请假天数',
          required: true,
        },
        {
          id: 'startTime',
          type: 'date',
          label: '开始时间',
          required: true,
        },
        {
          id: 'endTime',
          type: 'date',
          label: '结束时间',
          required: true,
        },
        {
          id: 'reason',
          type: 'textarea',
          label: '请假事由',
          required: true,
        },
      ],
    } as FormSchema,
    workflowSnapshot: {
      id: 'wf-leave-001',
      name: '请假审批流程',
      status: 'active',
      formSchemaId: 'leave-form',
      nodes: [
        {
          id: 'start-001',
          type: 'start',
          name: '发起节点',
          position: { x: 400, y: 100 },
          enabled: true,
        },
        {
          id: 'approval-001',
          type: 'approval',
          name: '部门经理审批',
          handler: { type: 'deptManager', mode: 'or' },
          position: { x: 400, y: 250 },
          enabled: true,
        },
        {
          id: 'end-001',
          type: 'end',
          name: '结束节点',
          position: { x: 400, y: 400 },
          enabled: true,
        },
      ],
      edges: [
        { id: 'edge-001', source: 'start-001', target: 'approval-001' },
        { id: 'edge-002', source: 'approval-001', target: 'end-001' },
      ],
    },
    changeLog: '新增结束时间字段，优化审批流程',
    changeType: 'minor',
    isActive: true,
    isCurrent: true,
    createdBy: 'admin',
    createdAt: '2026-03-15 14:30:00',
    publishedAt: '2026-03-15 15:00:00',
  },
  {
    id: 'VER-001-002',
    applicationId: 'APP-001',
    version: 2,
    versionName: 'v1.1.0',
    formSchemaSnapshot: {
      id: 'leave-form',
      name: '请假申请表',
      fields: [
        {
          id: 'leaveType',
          type: 'select',
          label: '请假类型',
          required: true,
          options: [
            { label: '病假', value: 'sick' },
            { label: '事假', value: 'personal' },
            { label: '年假', value: 'annual' },
          ],
        },
        {
          id: 'days',
          type: 'number',
          label: '请假天数',
          required: true,
        },
        {
          id: 'startTime',
          type: 'date',
          label: '开始时间',
          required: true,
        },
        {
          id: 'reason',
          type: 'textarea',
          label: '请假事由',
          required: true,
        },
      ],
    } as FormSchema,
    workflowSnapshot: {
      id: 'wf-leave-001',
      name: '请假审批流程',
      status: 'active',
      formSchemaId: 'leave-form',
      nodes: [
        {
          id: 'start-001',
          type: 'start',
          name: '发起节点',
          position: { x: 400, y: 100 },
          enabled: true,
        },
        {
          id: 'approval-001',
          type: 'approval',
          name: '部门经理审批',
          handler: { type: 'deptManager', mode: 'or' },
          position: { x: 400, y: 250 },
          enabled: true,
        },
        {
          id: 'end-001',
          type: 'end',
          name: '结束节点',
          position: { x: 400, y: 400 },
          enabled: true,
        },
      ],
      edges: [
        { id: 'edge-001', source: 'start-001', target: 'approval-001' },
        { id: 'edge-002', source: 'approval-001', target: 'end-001' },
      ],
    },
    changeLog: '简化审批流程，移除 HR 审批节点',
    changeType: 'minor',
    isActive: false,
    isCurrent: false,
    createdBy: 'admin',
    createdAt: '2026-02-10 10:00:00',
    publishedAt: '2026-02-10 11:00:00',
  },
  {
    id: 'VER-001-001',
    applicationId: 'APP-001',
    version: 1,
    versionName: 'v1.0.0',
    formSchemaSnapshot: {
      id: 'leave-form',
      name: '请假申请表',
      fields: [
        {
          id: 'leaveType',
          type: 'select',
          label: '请假类型',
          required: true,
          options: [
            { label: '病假', value: 'sick' },
            { label: '事假', value: 'personal' },
          ],
        },
        {
          id: 'days',
          type: 'number',
          label: '请假天数',
          required: true,
        },
        {
          id: 'reason',
          type: 'textarea',
          label: '请假事由',
          required: true,
        },
      ],
    } as FormSchema,
    workflowSnapshot: {
      id: 'wf-leave-001',
      name: '请假审批流程',
      status: 'active',
      formSchemaId: 'leave-form',
      nodes: [
        {
          id: 'start-001',
          type: 'start',
          name: '发起节点',
          position: { x: 400, y: 100 },
          enabled: true,
        },
        {
          id: 'approval-001',
          type: 'approval',
          name: '部门经理审批',
          handler: { type: 'deptManager', mode: 'or' },
          position: { x: 400, y: 250 },
          enabled: true,
        },
        {
          id: 'approval-002',
          type: 'approval',
          name: 'HR 审批',
          handler: { type: 'role', roleIds: ['hr'], mode: 'or' },
          position: { x: 400, y: 400 },
          enabled: true,
        },
        {
          id: 'end-001',
          type: 'end',
          name: '结束节点',
          position: { x: 400, y: 550 },
          enabled: true,
        },
      ],
      edges: [
        { id: 'edge-001', source: 'start-001', target: 'approval-001' },
        { id: 'edge-002', source: 'approval-001', target: 'approval-002' },
        { id: 'edge-003', source: 'approval-002', target: 'end-001' },
      ],
    },
    changeLog: '初始版本',
    changeType: 'major',
    isActive: false,
    isCurrent: false,
    createdBy: 'admin',
    createdAt: '2026-01-10 10:00:00',
    publishedAt: '2026-01-10 15:00:00',
  },
]

// ==================== 模板市场 Mock 数据 ====================

/**
 * Mock 模板列表
 */
export const mockTemplates: ApplicationTemplate[] = [
  {
    id: 'TPL-001',
    name: '通用请假申请模板',
    description: '适用于各类企业的标准请假申请流程，支持病假、事假、年假等多种假期类型',
    icon: '🏖️',
    category: 'hr',
    status: 'published',
    formSchemaSnapshot: {
      id: 'leave-form-template',
      name: '请假申请表',
      fields: [
        {
          id: 'leaveType',
          type: 'select',
          label: '请假类型',
          required: true,
          options: [
            { label: '病假', value: 'sick' },
            { label: '事假', value: 'personal' },
            { label: '年假', value: 'annual' },
            { label: '调休', value: 'compensatory' },
          ],
        },
        {
          id: 'days',
          type: 'number',
          label: '请假天数',
          required: true,
        },
        {
          id: 'startTime',
          type: 'date',
          label: '开始时间',
          required: true,
        },
        {
          id: 'endTime',
          type: 'date',
          label: '结束时间',
          required: true,
        },
        {
          id: 'reason',
          type: 'textarea',
          label: '请假事由',
          required: true,
        },
      ],
    } as FormSchema,
    workflowSnapshot: {
      id: 'wf-leave-template',
      name: '请假审批流程',
      status: 'active',
      formSchemaId: 'leave-form-template',
      nodes: [
        {
          id: 'start-001',
          type: 'start',
          name: '发起节点',
          position: { x: 400, y: 100 },
          enabled: true,
        },
        {
          id: 'approval-001',
          type: 'approval',
          name: '部门经理审批',
          handler: { type: 'deptManager', mode: 'or' },
          position: { x: 400, y: 250 },
          enabled: true,
        },
        {
          id: 'end-001',
          type: 'end',
          name: '结束节点',
          position: { x: 400, y: 400 },
          enabled: true,
        },
      ],
      edges: [
        { id: 'edge-001', source: 'start-001', target: 'approval-001' },
        { id: 'edge-002', source: 'approval-001', target: 'end-001' },
      ],
    },
    author: '系统管理员',
    authorId: 'admin',
    version: '1.0.0',
    tags: ['人事', '请假', '常用', '推荐'],
    downloads: 1250,
    rating: 4.8,
    reviewCount: 156,
    usageCount: 1250,
    features: [
      '支持多种假期类型',
      '自动计算请假天数',
      '部门经理一级审批',
      '移动端友好',
    ],
    createdAt: '2026-01-05 10:00:00',
    updatedAt: '2026-03-20 14:30:00',
    publishedAt: '2026-01-05 15:00:00',
  },
  {
    id: 'TPL-002',
    name: '差旅报销模板',
    description: '完整的差旅费用报销流程，包含交通、住宿、餐饮等费用明细',
    icon: '💰',
    category: 'finance',
    status: 'published',
    formSchemaSnapshot: {
      id: 'travel-expense-form',
      name: '差旅报销申请表',
      fields: [
        {
          id: 'travelDestination',
          type: 'input',
          label: '出差地点',
          required: true,
        },
        {
          id: 'travelDays',
          type: 'number',
          label: '出差天数',
          required: true,
        },
        {
          id: 'totalAmount',
          type: 'number',
          label: '报销总额',
          required: true,
        },
        {
          id: 'expenseDetails',
          type: 'textarea',
          label: '费用明细',
          required: true,
        },
      ],
    } as FormSchema,
    workflowSnapshot: {
      id: 'wf-travel-expense',
      name: '差旅报销流程',
      status: 'active',
      formSchemaId: 'travel-expense-form',
      nodes: [
        {
          id: 'start-001',
          type: 'start',
          name: '发起节点',
          position: { x: 400, y: 100 },
          enabled: true,
        },
        {
          id: 'approval-001',
          type: 'approval',
          name: '部门经理审批',
          handler: { type: 'deptManager', mode: 'or' },
          position: { x: 400, y: 250 },
          enabled: true,
        },
        {
          id: 'approval-002',
          type: 'approval',
          name: '财务审批',
          handler: { type: 'role', roleIds: ['finance'], mode: 'or' },
          position: { x: 400, y: 400 },
          enabled: true,
        },
        {
          id: 'end-001',
          type: 'end',
          name: '结束节点',
          position: { x: 400, y: 550 },
          enabled: true,
        },
      ],
      edges: [
        { id: 'edge-001', source: 'start-001', target: 'approval-001' },
        { id: 'edge-002', source: 'approval-001', target: 'approval-002' },
        { id: 'edge-003', source: 'approval-002', target: 'end-001' },
      ],
    },
    author: '财务部',
    authorId: 'user-finance',
    version: '2.1.0',
    tags: ['财务', '报销', '差旅', '推荐'],
    downloads: 890,
    rating: 4.6,
    reviewCount: 98,
    usageCount: 890,
    features: [
      '详细费用明细记录',
      '两级审批流程',
      '自动计算总额',
      '支持附件上传',
    ],
    createdAt: '2026-01-08 09:00:00',
    updatedAt: '2026-03-18 11:20:00',
    publishedAt: '2026-01-08 10:00:00',
  },
  {
    id: 'TPL-003',
    name: '采购申请模板',
    description: '办公用品、设备采购标准流程，支持多级审批和预算控制',
    icon: '🛒',
    category: 'admin',
    status: 'published',
    formSchemaSnapshot: {
      id: 'purchase-form-template',
      name: '采购申请表',
      fields: [
        {
          id: 'itemName',
          type: 'input',
          label: '采购物品',
          required: true,
        },
        {
          id: 'quantity',
          type: 'number',
          label: '数量',
          required: true,
        },
        {
          id: 'estimatedAmount',
          type: 'number',
          label: '预估金额',
          required: true,
        },
        {
          id: 'reason',
          type: 'textarea',
          label: '采购理由',
          required: true,
        },
      ],
    } as FormSchema,
    workflowSnapshot: {
      id: 'wf-purchase-template',
      name: '采购审批流程',
      status: 'active',
      formSchemaId: 'purchase-form-template',
      nodes: [
        {
          id: 'start-001',
          type: 'start',
          name: '发起节点',
          position: { x: 400, y: 100 },
          enabled: true,
        },
        {
          id: 'approval-001',
          type: 'approval',
          name: '部门经理审批',
          handler: { type: 'deptManager', mode: 'or' },
          position: { x: 400, y: 250 },
          enabled: true,
        },
        {
          id: 'condition-001',
          type: 'condition',
          name: '金额判断',
          condition: { field: 'estimatedAmount', operator: '>', value: 10000 },
          position: { x: 400, y: 400 },
          enabled: true,
        },
        {
          id: 'approval-002',
          type: 'approval',
          name: '总经理审批',
          handler: { type: 'role', roleIds: ['ceo'], mode: 'or' },
          position: { x: 250, y: 550 },
          enabled: true,
        },
        {
          id: 'end-001',
          type: 'end',
          name: '结束节点',
          position: { x: 400, y: 700 },
          enabled: true,
        },
      ],
      edges: [
        { id: 'edge-001', source: 'start-001', target: 'approval-001' },
        { id: 'edge-002', source: 'approval-001', target: 'condition-001' },
        { id: 'edge-003', source: 'condition-001', target: 'approval-002', label: '>10000' },
        { id: 'edge-004', source: 'condition-001', target: 'end-001', label: '≤10000' },
        { id: 'edge-005', source: 'approval-002', target: 'end-001' },
      ],
    },
    author: '行政部',
    authorId: 'user-admin',
    version: '1.5.0',
    tags: ['行政', '采购', '预算控制'],
    downloads: 567,
    rating: 4.5,
    reviewCount: 67,
    usageCount: 567,
    features: [
      '条件分支审批',
      '金额自动判断',
      '预算控制',
      '采购记录追踪',
    ],
    createdAt: '2026-01-12 14:00:00',
    updatedAt: '2026-03-15 16:45:00',
    publishedAt: '2026-01-12 15:00:00',
  },
  {
    id: 'TPL-004',
    name: '加班申请模板',
    description: '员工加班申请及调休管理，支持工作日、周末、节假日加班',
    icon: '⏰',
    category: 'hr',
    status: 'published',
    formSchemaSnapshot: {
      id: 'overtime-form-template',
      name: '加班申请表',
      fields: [
        {
          id: 'overtimeDate',
          type: 'date',
          label: '加班日期',
          required: true,
        },
        {
          id: 'overtimeHours',
          type: 'number',
          label: '加班时长（小时）',
          required: true,
        },
        {
          id: 'overtimeType',
          type: 'select',
          label: '加班类型',
          required: true,
          options: [
            { label: '工作日加班', value: 'weekday' },
            { label: '周末加班', value: 'weekend' },
            { label: '节假日加班', value: 'holiday' },
          ],
        },
        {
          id: 'reason',
          type: 'textarea',
          label: '加班原因',
          required: true,
        },
      ],
    } as FormSchema,
    workflowSnapshot: {
      id: 'wf-overtime-template',
      name: '加班审批流程',
      status: 'active',
      formSchemaId: 'overtime-form-template',
      nodes: [
        {
          id: 'start-001',
          type: 'start',
          name: '发起节点',
          position: { x: 400, y: 100 },
          enabled: true,
        },
        {
          id: 'approval-001',
          type: 'approval',
          name: '部门经理审批',
          handler: { type: 'deptManager', mode: 'or' },
          position: { x: 400, y: 250 },
          enabled: true,
        },
        {
          id: 'cc-001',
          type: 'cc',
          name: '抄送人事',
          ccUsers: { type: 'role', roleIds: ['hr'] },
          position: { x: 400, y: 400 },
          enabled: true,
        },
        {
          id: 'end-001',
          type: 'end',
          name: '结束节点',
          position: { x: 400, y: 550 },
          enabled: true,
        },
      ],
      edges: [
        { id: 'edge-001', source: 'start-001', target: 'approval-001' },
        { id: 'edge-002', source: 'approval-001', target: 'cc-001' },
        { id: 'edge-003', source: 'cc-001', target: 'end-001' },
      ],
    },
    author: '人事部',
    authorId: 'user-hr',
    version: '1.2.0',
    tags: ['人事', '加班', '考勤', '推荐'],
    downloads: 723,
    rating: 4.7,
    reviewCount: 89,
    usageCount: 723,
    features: [
      '多种加班类型',
      '自动计算调休',
      '抄送人事部门',
      '加班统计报表',
    ],
    createdAt: '2026-01-15 10:30:00',
    updatedAt: '2026-03-12 09:15:00',
    publishedAt: '2026-01-15 11:00:00',
  },
  {
    id: 'TPL-005',
    name: '合同审批模板',
    description: '企业合同签订标准流程，支持多部门会签和法务审核',
    icon: '📄',
    category: 'approval',
    status: 'published',
    formSchemaSnapshot: {
      id: 'contract-form-template',
      name: '合同审批表',
      fields: [
        {
          id: 'contractName',
          type: 'input',
          label: '合同名称',
          required: true,
        },
        {
          id: 'contractAmount',
          type: 'number',
          label: '合同金额',
          required: true,
        },
        {
          id: 'counterparty',
          type: 'input',
          label: '对方单位',
          required: true,
        },
        {
          id: 'contractPeriod',
          type: 'input',
          label: '合同期限',
          required: true,
        },
        {
          id: 'summary',
          type: 'textarea',
          label: '合同摘要',
          required: true,
        },
      ],
    } as FormSchema,
    workflowSnapshot: {
      id: 'wf-contract-template',
      name: '合同审批流程',
      status: 'active',
      formSchemaId: 'contract-form-template',
      nodes: [
        {
          id: 'start-001',
          type: 'start',
          name: '发起节点',
          position: { x: 400, y: 100 },
          enabled: true,
        },
        {
          id: 'approval-001',
          type: 'approval',
          name: '部门经理审批',
          handler: { type: 'deptManager', mode: 'or' },
          position: { x: 400, y: 250 },
          enabled: true,
        },
        {
          id: 'approval-002',
          type: 'approval',
          name: '法务审核',
          handler: { type: 'role', roleIds: ['legal'], mode: 'or' },
          position: { x: 400, y: 400 },
          enabled: true,
        },
        {
          id: 'approval-003',
          type: 'approval',
          name: '总经理审批',
          handler: { type: 'role', roleIds: ['ceo'], mode: 'or' },
          position: { x: 400, y: 550 },
          enabled: true,
        },
        {
          id: 'end-001',
          type: 'end',
          name: '结束节点',
          position: { x: 400, y: 700 },
          enabled: true,
        },
      ],
      edges: [
        { id: 'edge-001', source: 'start-001', target: 'approval-001' },
        { id: 'edge-002', source: 'approval-001', target: 'approval-002' },
        { id: 'edge-003', source: 'approval-002', target: 'approval-003' },
        { id: 'edge-004', source: 'approval-003', target: 'end-001' },
      ],
    },
    author: '法务部',
    authorId: 'user-legal',
    version: '1.0.0',
    tags: ['审批', '合同', '法务'],
    downloads: 445,
    rating: 4.4,
    reviewCount: 52,
    usageCount: 445,
    features: [
      '三级审批流程',
      '法务专业审核',
      '合同归档管理',
      '风险提示',
    ],
    createdAt: '2026-01-20 09:00:00',
    updatedAt: '2026-03-10 13:30:00',
    publishedAt: '2026-01-20 10:00:00',
  },
  {
    id: 'TPL-006',
    name: '用章申请模板',
    description: '公司印章使用申请流程，支持合同章、公章、财务章等',
    icon: '🔖',
    category: 'admin',
    status: 'published',
    formSchemaSnapshot: {
      id: 'seal-form-template',
      name: '用章申请表',
      fields: [
        {
          id: 'sealType',
          type: 'select',
          label: '印章类型',
          required: true,
          options: [
            { label: '公章', value: 'official' },
            { label: '合同章', value: 'contract' },
            { label: '财务章', value: 'finance' },
          ],
        },
        {
          id: 'purpose',
          type: 'textarea',
          label: '用章事由',
          required: true,
        },
        {
          id: 'documentName',
          type: 'input',
          label: '文件名称',
          required: true,
        },
      ],
    } as FormSchema,
    workflowSnapshot: {
      id: 'wf-seal-template',
      name: '用章审批流程',
      status: 'active',
      formSchemaId: 'seal-form-template',
      nodes: [
        {
          id: 'start-001',
          type: 'start',
          name: '发起节点',
          position: { x: 400, y: 100 },
          enabled: true,
        },
        {
          id: 'approval-001',
          type: 'approval',
          name: '部门经理审批',
          handler: { type: 'deptManager', mode: 'or' },
          position: { x: 400, y: 250 },
          enabled: true,
        },
        {
          id: 'approval-002',
          type: 'approval',
          name: '行政审批',
          handler: { type: 'role', roleIds: ['admin'], mode: 'or' },
          position: { x: 400, y: 400 },
          enabled: true,
        },
        {
          id: 'end-001',
          type: 'end',
          name: '结束节点',
          position: { x: 400, y: 550 },
          enabled: true,
        },
      ],
      edges: [
        { id: 'edge-001', source: 'start-001', target: 'approval-001' },
        { id: 'edge-002', source: 'approval-001', target: 'approval-002' },
        { id: 'edge-003', source: 'approval-002', target: 'end-001' },
      ],
    },
    author: '行政部',
    authorId: 'user-admin',
    version: '1.1.0',
    tags: ['行政', '用章', '印章管理'],
    downloads: 334,
    rating: 4.3,
    reviewCount: 41,
    usageCount: 334,
    features: [
      '多种印章类型',
      '用章记录追踪',
      '行政统一管理',
      '安全审核',
    ],
    createdAt: '2026-01-25 11:00:00',
    updatedAt: '2026-03-08 15:20:00',
    publishedAt: '2026-01-25 12:00:00',
  },
]

/**
 * Mock 模板评论
 */
export const mockTemplateReviews: TemplateReview[] = [
  {
    id: 'REV-001',
    templateId: 'TPL-001',
    userId: 'user-001',
    userName: '张三',
    userAvatar: 'https://api.multiavatar.com/张三.png',
    rating: 5,
    content: '非常好用的请假模板，流程简洁明了，我们公司直接安装使用了！',
    likeCount: 23,
    isLiked: false,
    createdAt: '2026-03-15 10:30:00',
  },
  {
    id: 'REV-002',
    templateId: 'TPL-001',
    userId: 'user-002',
    userName: '李四',
    userAvatar: 'https://api.multiavatar.com/李四.png',
    rating: 4,
    content: '整体不错，建议增加半天假的选项。',
    likeCount: 15,
    isLiked: false,
    createdAt: '2026-03-10 14:20:00',
  },
  {
    id: 'REV-003',
    templateId: 'TPL-002',
    userId: 'user-003',
    userName: '王五',
    userAvatar: 'https://api.multiavatar.com/王五.png',
    rating: 5,
    content: '差旅报销模板很专业，费用明细分类清晰，财务审批也很方便。',
    likeCount: 18,
    isLiked: false,
    createdAt: '2026-03-12 09:15:00',
  },
  {
    id: 'REV-004',
    templateId: 'TPL-003',
    userId: 'user-004',
    userName: '赵六',
    userAvatar: 'https://api.multiavatar.com/赵六.png',
    rating: 4,
    content: '采购流程的条件分支很实用，大额采购自动走总经理审批。',
    likeCount: 12,
    isLiked: false,
    createdAt: '2026-03-08 16:45:00',
  },
  {
    id: 'REV-005',
    templateId: 'TPL-004',
    userId: 'user-005',
    userName: '孙七',
    userAvatar: 'https://api.multiavatar.com/孙七.png',
    rating: 5,
    content: '加班模板考虑得很周全，工作日、周末、节假日都有区分。',
    likeCount: 20,
    isLiked: false,
    createdAt: '2026-03-05 11:30:00',
  },
]

/**
 * Mock 模板安装记录
 */
export const mockTemplateInstallRecords: TemplateInstallRecord[] = [
  {
    id: 'INST-001',
    templateId: 'TPL-001',
    templateName: '通用请假申请模板',
    userId: '1',
    userName: '当前用户',
    applicationId: 'APP-001',
    success: true,
    installedAt: '2026-03-20 10:30:00',
  },
  {
    id: 'INST-002',
    templateId: 'TPL-002',
    templateName: '差旅报销模板',
    userId: '1',
    userName: '当前用户',
    applicationId: 'APP-002',
    success: true,
    installedAt: '2026-03-18 14:20:00',
  },
  {
    id: 'INST-003',
    templateId: 'TPL-003',
    templateName: '采购申请模板',
    userId: '1',
    userName: '当前用户',
    applicationId: 'APP-003',
    success: true,
    installedAt: '2026-03-15 09:15:00',
  },
]
